POST http://localhost:3000/api/assets/add_asset
content-type: application/json

{
    "name": "something",
    "serial_number": "123",
    "model": "something",
    "department": "something",
    "price": "1000",
    "location": "something",
    "supplier": "something",
    "condition": 1,
    "last_pm_date": "2017-09-14",
    "last_failure_date": "2017-09-14",
    "last_fix_date": "2017-09-14"
}

###
GET http://localhost:3000/api/assets
content-type: application/json

### 
GET http://localhost:3000/api/assets/edited2
content-type: application/json

### 
PUT http://localhost:3000/api/assets/5ea72c367bf92022476a79dd
content-type: application/json

{
    "name": "edited",
    "serial_number": "edited2",
    "model": "edited",
    "department": "edited",
    "price": "1000",
    "location": "edited",
    "supplier": "edited",
    "condition": 1,
    "last_pm_date": "2017-09-14",
    "last_failure_date": "2017-09-14",
    "last_fix_date": "2017-09-14"
}



### 
POST http://localhost:3000/api/assets/report_asset
content-type: application/json

{
    "name_of_reporter":"nada",
    "title":"report",
    "asset":"5eab1f5a5ddc7d1a5edf0489",
    "body":"this is report body",
    "open_date":"2017-09-14",
    "finish_date":"2017-09-14"
}

###
GET http://localhost:3000/api/reports
content-type: application/json


