### test assets routes

POST http://localhost:3000/api/assets/add_asset
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlYjcxZmY5MjBlYTc3NWZhNjY0ZjZhOSIsImlhdCI6MTU4OTA1OTU3NywiZXhwIjoxNTg5MDYzMTc3fQ.PTMuB71TbQMOuKz7CG8dvZ_UtQ-o6K6dShZyhjMRWUY

{
    "name": "Ventilator",
    "serial_number": "35820371w1",
    "model": "XY10",
    "department": "cardiology",
    "price": "1000",
    "location": "something",
    "supplier": "something",
    "condition": "Scrapped",
    "last_pm_date": "2017-09-14",
    "last_failure_date": "2017-09-14",
    "last_fix_date": "2017-09-14"
}

###
GET http://localhost:3000/api/assets
content-type: application/json

### 
GET http://localhost:3000/api/assets/5ea72c367bf92022476a79dd
content-type: application/json

### 
PUT http://localhost:3000/api/assets/5ea72c367bf92022476a79dd
content-type: application/json

{
    "name": "edited",
    "serial_number": "edited2",
    "model": "edited",
    "department": "edited",
    "price": "1000",
    "location": "edited",
    "supplier": "edited",
    "condition": 1,
    "last_pm_date": "2017-09-14",
    "last_failure_date": "2017-09-14",
    "last_fix_date": "2017-09-14"
}


### test reports routes
### 
POST http://localhost:3000/api/assets/report_asset
content-type: application/json

{
    "name_of_reporter":"nada",
    "title":"report",
    "asset":"5eab1f5a5ddc7d1a5edf0489",
    "body":"this is report body",
    "open_date":"2017-09-14",
    "finish_date":"2017-09-14"
}

###
GET http://localhost:3000/api/reports
content-type: application/json

### test employees routes
POST http://localhost:3000/api/employees/add_employee
content-type: application/json

{
    "ssn":"1234",
    "name":"nada",
    "position":"Manager",
    "phone_number":"010",
    "gender":"Female",
    "shift_start":"2017-09-14",
    "shift_end":"2017-09-14"
}

###
GET http://localhost:3000/api/employees
content-type: application/json

### 
GET http://localhost:3000/api/employees/5eb476385319c47d89133849
content-type: application/json

### 
PUT http://localhost:3000/api/employees/5eab305ee8b082327ae6722c
content-type: application/json

{
    "ssn":"123",
    "name":"edited",
    "position":"Manager",
    "phone_number":"010",
    "gender":"Female",
    "shift_start":"2017-09-14",
    "shift_end":"2017-09-14"
}

### PMS testing

POST http://localhost:3000/api/pms/add_pm
content-type: application/json

{
    "title":"pm title",
    "asset":"5eb4741e5fa94a7ab088328e",
    "instructions":["1","2","3"],
    "assigned_to":"5eb449dddc3c7e398326af1e",
    "status":"Done",
    "schedules":"Every week"
}

###
GET http://localhost:3000/api/pms
content-type: application/json

### 
GET http://localhost:3000/api/pms/5eb476525319c47d8913384a
content-type: application/json

### 
PUT http://localhost:3000/api/pms/5eb45e1771e3b561a7b9a149
content-type: application/json

{
    "title":"pm title edited",
    "asset":"5eb456ae26aaa05a87eb7a9c",
    "instructions":["1","2","3","4"],
    "assigned_to":"5eb46b3931859d6f72f724fb",
    "status":"Done",
    "schedules":"Every week"
}

### 
## login and registeration

POST http://localhost:3000/api/auth/register
content-type: application/json

{
    "name":"nada2",
    "email":"nada2@nada2.com",
    "password":"nada2",
    "role":"Supervisor",
    "department":"radiology"
}

###

POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "email":"nadosh1@gmail.com",
    "password":"1998"
}