### Test assets routes
POST  http://localhost:3000/api/assets
Content-Type: application/json

{
    "name":"Infusion Pump",
    "serial_number":"‫‪20370613‬‬",
    "model":"optima pt", 
    "brand":"kabi fresenuis",
    "department":"cardiology", 
    "COO":"france", 
    "operation_date":"2005-01-31",
    "warranty_period":"2", 
    "supply_company":"egyptian group",
    "parts":"NA", 
    "maintenance_company":"NA", 
    "contract_type":"NA", 
    "description":"An infusion pump is a medical device that delivers fluids, such as nutrients and medications, into a patient’s body in controlled amounts.It offers significant advantages over manual administration of fluids,including the ability to deliver fluids in very small volumes, and the ability to deliver fluids at precisely programmed rates or automated intervals.",
    "classification":"life support devices", 
    "lifetime":"10", 
    "proper_freq_of_use":"NA",
    "electricity_sensitivity":"Class |", 
    "risk_level":"A", 
    "work_env":"-Operating Temperature: 5 C – 40 C \\n -Humidity: 20% – 90 %, no condensation. \\n -Atmospheric pressure: 700 hPa to 1060 hPa. \\n -Fully recharge the equipment before usage to avoid any risks caused by micro power cuts in the mains supply.",
    "efficiency":"excellent", 
    "alarms": ["Upstream occlusion alarm" ,
                "Air detection alarm" ,
                "Air volume alarm" ,
                "Door alarm" ,
                "Global alarm ",
                "Battery alarm" ,
                "End of infusion alarm" ,
                "Downstream occlusion alarm" ,
                "Tube absence alarm" ,
                "Drip detector alarm- under flow" ,
                "Drip detector alarm- over flow" ,
                "Pressure limit alarm" ,
                "Free flow alarm ",
                "Mobile clamp absence alarm"],
    "accessories":"NA", 
    "sterilization":"1.Disconnect the base from its mains supply before cleaning. 2.Do not place in AUTOCLAVE nor immerse device. 3.If the device is placed in high contamination risk unit, leave it in the room during disinfecting, after having it disinfected with a moist cloth. 4.Use a cloth soaked in DETERGERNT-DISINFECTANT diluted with water to destroy microorganisms.  5.Avoid abrasive scrubbing that could scratch the casing, do not rinse or wipe the surfaces. 6.Take care of ALCOHOL-based sprays (20%-40% Alcohol) They lead to small cracks in plastic."
}

###
GET http://localhost:3000/api/assets
content-type: application/json

### 
GET http://localhost:3000/api/assets/5ec357326d554f752ae20229
content-type: application/json 

### test reports routes
### 
POST http://localhost:3000/api/assets/report_asset
content-type: application/json

{
    "name_of_reporter":"nada",
    "title":"report",
    "asset":"5eab1f5a5ddc7d1a5edf0489",
    "body":"this is report body",
    "open_date":"2017-09-14",
    "finish_date":"2017-09-14"
}

###
GET http://localhost:3000/api/reports
content-type: application/json

### test employees routes
POST http://localhost:3000/api/employees/add_employee
content-type: application/json

{
    "ssn":"1234",
    "name":"nada",
    "position":"Manager",
    "phone_number":"010",
    "gender":"Female",
    "shift_start":"2017-09-14",
    "shift_end":"2017-09-14"
}

###
GET http://localhost:3000/api/employees
content-type: application/json

### 
GET http://localhost:3000/api/employees/5eb476385319c47d89133849
content-type: application/json

### 
PUT http://localhost:3000/api/employees/5eab305ee8b082327ae6722c
content-type: application/json

{
    "ssn":"123",
    "name":"edited",
    "position":"Manager",
    "phone_number":"010",
    "gender":"Female",
    "shift_start":"2017-09-14",
    "shift_end":"2017-09-14"
}

### PMS testing

POST http://localhost:3000/api/pms/add_pm
content-type: application/json

{
    "title":"changing the battery",
    "asset":"5ec57529b7c5101af4dd13eb",
    "instructions":"This procedure, which includes changing the battery, should be carried out by a qualified technician. Any abnormal functioning must be reported to the qualified technician and the pump should not be used.",
    "schedules":"every 3 years"
}

###
GET http://localhost:3000/api/pms
content-type: application/json

### 
GET http://localhost:3000/api/pms/5ec050ef6c57db3bcc2ad7b9
content-type: application/json

### 
PUT http://localhost:3000/api/pms/edit/5ec050ef6c57db3bcc2ad7b9
content-type: application/json

{
    "report_title":"hhh"
}

### 
## login and registeration

POST http://localhost:3000/api/auth/register
content-type: application/json

{
    "name":"Ahmad",
    "email":"ahmad@gmail.com",
    "password":"ahmad",
    "role":"Technician",
    "department":"reception"
}

###

POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "email":"nada@nada.com",
    "password":"nada"
}

###
GET http://localhost:3000/api/users
content-type: application/json

## WOs

###

POST http://localhost:3000/api/wos/create
content-type: application/json

{
    "title":"Title",
    "asset":"5ebed42c307ec31364057238",
    "instructions":"Instructions",
    "assigned_to":"5ec05796f3afb54fa97a750a",
    "priority":"Urgent",
    "importance":"Important",
    "issue_date":"2017-09-14",
    "due_date":"2017-09-14",
    "notes":"Notes",
    "report_title":"Title",
    "report_body":"Body"
}